package com.allan.entity;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   全国行政区域数据库
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_china_area
 */
public class ChinaArea {
    /**
     * Database Column Remarks:
     *   地区编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   地区名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.area_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String areaName;

    /**
     * Database Column Remarks:
     *   上级地区编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.parent_id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   地区简称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.short_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   区域类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.level_type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer levelType;

    /**
     * Database Column Remarks:
     *   城市编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.city_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String cityCode;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.zip_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   区域全称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.merger_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String mergerName;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.longitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private BigDecimal longitude;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.latitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private BigDecimal latitude;

    /**
     * Database Column Remarks:
     *   拼音名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_china_area.city_name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String cityNameEn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.id
     *
     * @return the value of t_china_area.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.id
     *
     * @param id the value for t_china_area.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.area_name
     *
     * @return the value of t_china_area.area_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.area_name
     *
     * @param areaName the value for t_china_area.area_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.parent_id
     *
     * @return the value of t_china_area.parent_id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.parent_id
     *
     * @param parentId the value for t_china_area.parent_id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.short_name
     *
     * @return the value of t_china_area.short_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.short_name
     *
     * @param shortName the value for t_china_area.short_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.level_type
     *
     * @return the value of t_china_area.level_type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.level_type
     *
     * @param levelType the value for t_china_area.level_type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setLevelType(Integer levelType) {
        this.levelType = levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.city_code
     *
     * @return the value of t_china_area.city_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.city_code
     *
     * @param cityCode the value for t_china_area.city_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.zip_code
     *
     * @return the value of t_china_area.zip_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.zip_code
     *
     * @param zipCode the value for t_china_area.zip_code
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.merger_name
     *
     * @return the value of t_china_area.merger_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.merger_name
     *
     * @param mergerName the value for t_china_area.merger_name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.longitude
     *
     * @return the value of t_china_area.longitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.longitude
     *
     * @param longitude the value for t_china_area.longitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.latitude
     *
     * @return the value of t_china_area.latitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.latitude
     *
     * @param latitude the value for t_china_area.latitude
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_china_area.city_name_en
     *
     * @return the value of t_china_area.city_name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getCityNameEn() {
        return cityNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_china_area.city_name_en
     *
     * @param cityNameEn the value for t_china_area.city_name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCityNameEn(String cityNameEn) {
        this.cityNameEn = cityNameEn == null ? null : cityNameEn.trim();
    }
}