package com.allan.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   酒店所在城市基础数据
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_hotel_city
 */
public class HotelCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.pname
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.city_initial
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String cityInitial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.province
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.province_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String provinceEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.country
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.country_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String countryEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.create_time
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.adcode
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private String adcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel_city.is_show
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    private Integer isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.id
     *
     * @return the value of t_hotel_city.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.id
     *
     * @param id the value for t_hotel_city.id
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.type
     *
     * @return the value of t_hotel_city.type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.type
     *
     * @param type the value for t_hotel_city.type
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.pname
     *
     * @return the value of t_hotel_city.pname
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.pname
     *
     * @param pname the value for t_hotel_city.pname
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.name
     *
     * @return the value of t_hotel_city.name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.name
     *
     * @param name the value for t_hotel_city.name
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.city_initial
     *
     * @return the value of t_hotel_city.city_initial
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getCityInitial() {
        return cityInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.city_initial
     *
     * @param cityInitial the value for t_hotel_city.city_initial
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCityInitial(String cityInitial) {
        this.cityInitial = cityInitial == null ? null : cityInitial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.name_en
     *
     * @return the value of t_hotel_city.name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.name_en
     *
     * @param nameEn the value for t_hotel_city.name_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.province
     *
     * @return the value of t_hotel_city.province
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.province
     *
     * @param province the value for t_hotel_city.province
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.province_en
     *
     * @return the value of t_hotel_city.province_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getProvinceEn() {
        return provinceEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.province_en
     *
     * @param provinceEn the value for t_hotel_city.province_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setProvinceEn(String provinceEn) {
        this.provinceEn = provinceEn == null ? null : provinceEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.country
     *
     * @return the value of t_hotel_city.country
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.country
     *
     * @param country the value for t_hotel_city.country
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.country_en
     *
     * @return the value of t_hotel_city.country_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getCountryEn() {
        return countryEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.country_en
     *
     * @param countryEn the value for t_hotel_city.country_en
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCountryEn(String countryEn) {
        this.countryEn = countryEn == null ? null : countryEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.create_time
     *
     * @return the value of t_hotel_city.create_time
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.create_time
     *
     * @param createTime the value for t_hotel_city.create_time
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.adcode
     *
     * @return the value of t_hotel_city.adcode
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.adcode
     *
     * @param adcode the value for t_hotel_city.adcode
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode == null ? null : adcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel_city.is_show
     *
     * @return the value of t_hotel_city.is_show
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel_city.is_show
     *
     * @param isShow the value for t_hotel_city.is_show
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }
}