package com.allan.mapper;

import com.allan.entity.ChinaArea;

public interface ChinaAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int insert(ChinaArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int insertSelective(ChinaArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    ChinaArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int updateByPrimaryKeySelective(ChinaArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_china_area
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int updateByPrimaryKey(ChinaArea record);
}