package com.allan.mapper;

import com.allan.entity.HotelCity;

public interface HotelCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int insert(HotelCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int insertSelective(HotelCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    HotelCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int updateByPrimaryKeySelective(HotelCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hotel_city
     *
     * @mbg.generated Sun Mar 29 16:53:14 CST 2020
     */
    int updateByPrimaryKey(HotelCity record);
}